using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace BANDONGHO_TTCS_Client
{
    public partial class UCTrangChu : DevExpress.XtraEditors.XtraUserControl
    {
        private static UCTrangChu _instance;
        public static UCTrangChu Instance
        {
            get
            {
                if (_instance == null)
                {
                    _instance = new UCTrangChu();
                }
                return _instance;
            }
        }
        public UCTrangChu()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
 



        }
        private void UCDongHo_Load(object sender, EventArgs e)
        {
            mainPanel.Controls.Clear();
            DongHo d;
            v_DONG_HOTableAdapter.Fill(dSet.V_DONG_HO);
            bdsDongHo.DataSource = dSet.V_DONG_HO;
            for (int i = 0; i < bdsDongHo.Count; i++)
            {
                d = new DongHo();
                d.maDH = ((DataRowView)bdsDongHo[i])[0].ToString();
                d.ten = ((DataRowView)bdsDongHo[i])[1].ToString();
                d.slTon = (int)((DataRowView)bdsDongHo[i])[2];
                d.gia = double.Parse(((DataRowView)bdsDongHo[i])[3].ToString());
                d.hinhAnh = ((DataRowView)bdsDongHo[i])[4].ToString();
                d.hang = ((DataRowView)bdsDongHo[i])[5].ToString();
                d.loai = ((DataRowView)bdsDongHo[i])[6].ToString();
                d.moTa = ((DataRowView)bdsDongHo[i])[7].ToString();
                d.giaSauGiam = double.Parse(((DataRowView)bdsDongHo[i])[8].ToString());
                d.giamGia = double.Parse(((DataRowView)bdsDongHo[i])[9].ToString());
                if(d.slTon > 0)
                {
                    d.initUI();
                    this.mainPanel.Controls.Add(d);
                }

            }
        }

        private void button2_Click(object sender, EventArgs e)
        {
            UCDongHo_Load(sender, e);

        }

        private void button1_Click(object sender, EventArgs e)
        {
        }
    }
}
