USE BANDONGHO_TTCS
GO
ALTER PROC SP_TKDT_NV
@tungay date, @denngay date
AS
SELECT n.MANV, n.HO, n.TEN, SUM(c.DONGIA*c.SOLUONG) DOANHTHU
FROM NHANVIEN n, PHIEUDAT p, CT_PD c
WHERE (p.NGAYDAT BETWEEN @tungay AND @denngay)
AND n.MANV=p.MANV AND c.MAPHIEUDAT=p.MAPHIEUDAT
AND p.TRANGTHAI = N'Hoàn tất'
GROUP BY n.MANV, n.HO, n.TEN
ORDER BY DOANHTHU DESC