USE BANDONGHO_TTCS
GO
CREATE PROC SP_TKDT_SP
@tungay date, @denngay date
AS
SELECT d.MADONGHO, d.TENDONGHO, SUM(c.DONGIA*c.SOLUONG) DOANHTHU
FROM DONGHO d, PHIEUDAT p, CT_PD c
WHERE (p.NGAYDAT BETWEEN @tungay AND @denngay)
AND d.MADONGHO=c.MADONGHO AND c.MAPHIEUDAT=p.MAPHIEUDAT
AND p.TRANGTHAI = N'Hoàn tất'
GROUP BY d.MADONGHO, d.TENDONGHO
ORDER BY DOANHTHU DESC